default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pai
  password: tigers
  host: db

development:
  <<: *default
  database: pai_book_mgt_dev

test:
  <<: *default
  database: pai_book_mgt_test

production:
  <<: *default
  database: pai_book_mgt_prod
  username: pai_book_mgt
  password: <%= ENV["PAI_BOOK_MGT_DATABASE_PASSWORD"] %>
